#!/bin/sh

maxDesktops=6
monitorCount=$(bspc query -M | wc -l)

if [ $monitorCount -gt 1 ]; then
    mlist=" abcd"
    dmax=$(($maxDesktops/$monitorCount))
    dcurrent=1
    i=1
    for monitor in $(bspc query -M); do
        dstring=""
        for d in `seq 1 $dmax`; do
            dstring="$dstring${mlist:$i:1}$dcurrent "
            let dcurrent++
        done
        bspc monitor $monitor -n $i -d $dstring
        let i++
    done
    unset i mlist
else
    eval bspc monitor -d {1..$maxDesktops}
fi

desktop_config() {
    bspc config $1 $2
    for M in $(bspc query -M); do
        bspc config -m $M $1 $2
    done
}

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# Resizing/moving
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Visual options
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config normal_border_color   "#2a2d30"
bspc config active_border_color   "#515861"
bspc config focused_border_color  "#4d1e8a"
bspc config presel_feedback_color "#4d1e8a"

for desktop in $(bspc query -D); do
  bspc config -d $desktop border_width 1;
  bspc config -d $desktop window_gap 8;
done

# Rules
# bspc rule -a Thunar pseudo_tiled=on
bspc rule -a feh          state=floating center
bspc rule -a Sxiv         state=floating center
bspc rule -a mpv          state=floating center
bspc rule -a KeePassXC    state=floating
bspc rule -a Pavucontrol  state=floating center
bspc rule -a 'firefox:Toolkit:Picture-in-Picture' state=floating

bspc rule -a Emacs        state=tiled
bspc rule -a Zathura      state=tiled

bspc config external_rules_command ~/.config/bspwm/external_rules


# ~/.config/bspwm/lemonbar/panel &
~/.config/polybar/launch.sh

# Fix correct padding
# bspc config -m 1 top_padding 20 

