#!/bin/sh

if [[ $# -eq 0  ]]; then
    echo "No filename specified"
    exit 1
elif [[ $# -eq 2 ]]; then
    path=$2
else
    path=~/Appimage
fi

app="$(find $path -iname $1'*' | tail -1 )"

if [ -z "$app" ]; then
    echo "No AppImage found for $1"
    exit 1
fi

sh -c $app
