#!/bin/bash

mailfifo=/tmp/mail_count

[ -p $mailfifo ] || mkfifo $mailfifo


if [[ $# -eq 0  ]]; then
    watch_path=~/Mail/*/Inbox/new
else
    watch_path=$1
fi

function mailcount() {
    echo "$(find $watch_path -type f | wc -l)"
}
function increment() {
    newmails=$[newmails +1]
    update_fifo
}
function decrement() {
    newmails=$[newmails -1]
    update_fifo
}
function update_fifo() {
    if (( $newmails > 0 )); then
        echo $newmails > $mailfifo
    else
        echo "" > $mailfifo
    fi
}

newmails=$(mailcount)
update_fifo

inotifywait -q -m $watch_path -e create -e moved_to -e moved_from  -e delete |
    while read path action file; do
        case "$action" in
            "CREATE" | "MOVED_TO" )
                increment $path $file
                ;;
            "MOVED_FROM" | "DELETE" )
                decrement $path $file
                ;;
        esac
    done


# notify-send -t 12000 -i '/usr/share/icons/Adwaita/16x16/status/mail-unread-symbolic.symbolic.png' \
#     "New mail in $bo" "`grep -m 1 ^From: $f`\n`grep -m 1 ^Subject: $f`"
